<?php
namespace Fluxion;
/** @var SetupView $this */
?>

<!doctype html>
<html lang="pt-br">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>Setup</title>
    <style>

        body {
            background-color: #f6f6f6;
            font-family: sans-serif;
            -webkit-font-smoothing: antialiased;
            font-size: 14px;
            line-height: 1.4;
            margin: 0;
            padding: 0;
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
            width: 100%;
        }

        .text-red {color: #ff6b68}
        .text-pink {color: #ff85af}
        .text-purple {color: #d066e2}
        .text-deep-purple {color: #673ab7}
        .text-indigo {color: #3f51b5}
        .text-blue {color: #2196f3}
        .text-light-blue {color: #03a9f4}
        .text-white {color: #ffffff}
        .text-cyan {color: #00bcd4}
        .text-teal {color: #39bbb0}
        .text-green {color: #32c787}
        .text-light-green {color: #8bc34a}
        .text-lime {color: #cddc39}
        .text-yellow {color: #ffeb3b}
        .text-amber {color: #ffc721}
        .text-orange {color: #ff9800}
        .text-deep-orange {color: #ff5722}
        .text-brown {color: #795548}
        .text-gray {color: #9e9e9e}
        .text-blue-gray {color: #607d8b}
        .text-black {color: #000000}

        pre {
            background-color: #343a40;
            border-radius: 2px;
            padding: 1.5rem;
            display: block;
            font-size: 87.5%;
            color: #fff;
            margin: 20px;
            overflow: auto;
        }

    </style>
</head>
<body>
<?=$this->content?>
</body>
</html>